spring.datasource.url=jdbc:mysql://localhost:3306/forum_hub
spring.datasource.username=root
spring.datasource.password=bancodedados
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.application.name=ForumHub

Server.error.include-stracktrace=never

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=246810

api.security.token.expiration=2